INSERT INTO CBS_SCHEMA.PERSONAL_DATA_INDIVIDUALS (
    REPORTINGDATE,
    CUSTOMERIDENTIFICATIONNUMBER,
    FIRSTNAME,
    MIDDLENAMES,
    SURNAME,
    GENDER,
    DATEOFBIRTH,
    MARITALSTATUS,
    NUMBEROFDEPENDANTS,
    DISABILITYSTATUS,
    DISABILITYTYPE,
    CITIZENSHIP,
    NATIONALITY,
    RESIDENCE,
    RESIDENCESTATUS,
    EMPLOYMENTSTATUS,
    OCCUPATION,
    EMPLOYERNAME,
    EMPLOYERADDRESS,
    SECTOREMPLOYER,
    INCOMERANGE,
    EDUCATIONLEVEL,
    IDENTIFICATIONTYPE,
    IDENTIFICATIONNUMBER,
    ISSUINGCOUNTRY,
    ISSUINGAUTHORITY,
    ISSUEDATE,
    EXPIRYDATE,
    MOBILENUMBER,
    ALTMOBILENUMBER,
    EMAILADDRESS,
    ALTEMAILADDRESS,
    POSTALADDRESS,
    PHYSICALADDRESS,
    REGION,
    DISTRICT,
    WARD,
    STREET,
    HOUSENUMBER,
    POSTALCODE,
    COUNTRY,
    GPSCOORDINATES,
    NEXTOFKINNAME,
    NEXTOFKINRELATIONSHIP,
    NEXTOFKINMOBILENUMBER,
    NEXTOFKINEMAILADDRESS,
    NEXTOFKINADDRESS,
    NEXTOFKINREGION,
    NEXTOFKINDISTRICT,
    NEXTOFKINWARD,
    NEXTOFKINSTREET,
    NEXTOFKINHOUSENUMBER,
    NEXTOFKINPOSTALCODE,
    NEXTOFKINCOUNTRY,
    NEXTOFKINGPSCOORDINATES,
    KYCSTATUS,
    KYCDATE,
    KYCEXPIRYDATE,
    RISKRATING,
    RISKRATINGDATE,
    PEPSTATUS,
    PEPCLASSIFICATION,
    PEPPOSITION,
    PEPCOUNTRY,
    PEPRELATIONSHIP,
    SANCTIONSSTATUS,
    SANCTIONSLIST,
    SANCTIONSDATE,
    SANCTIONSCOUNTRY,
    VILLAGE
) VALUES (
    '061020251720', -- REPORTINGDATE (DDMMYYYYHHMM format)
    'CUST001', -- CUSTOMERIDENTIFICATIONNUMBER
    'John', -- FIRSTNAME
    'Middle', -- MIDDLENAMES
    'Doe', -- SURNAME
    'Male', -- GENDER
    '15061985', -- DATEOFBIRTH (DDMMYYYY)
    'Married', -- MARITALSTATUS
    2, -- NUMBEROFDEPENDANTS
    'No', -- DISABILITYSTATUS
    '', -- DISABILITYTYPE
    'Tanzanian', -- CITIZENSHIP
    'Tanzania', -- NATIONALITY
    'Dar es Salaam', -- RESIDENCE
    'Permanent', -- RESIDENCESTATUS
    'Employed', -- EMPLOYMENTSTATUS
    'Engineer', -- OCCUPATION
    'Tech Corp', -- EMPLOYERNAME
    '123 Tech Street', -- EMPLOYERADDRESS
    'Technology', -- SECTOREMPLOYER
    '50000', -- INCOMERANGE
    'University', -- EDUCATIONLEVEL
    'Passport', -- IDENTIFICATIONTYPE
    'P12345678', -- IDENTIFICATIONNUMBER
    'Tanzania', -- ISSUINGCOUNTRY
    'Immigration Office', -- ISSUINGAUTHORITY
    '01012020', -- ISSUEDATE (DDMMYYYY)
    '01012030', -- EXPIRYDATE (DDMMYYYY)
    '+255123456789', -- MOBILENUMBER
    '', -- ALTMOBILENUMBER
    'john.doe@email.com', -- EMAILADDRESS
    '', -- ALTEMAILADDRESS
    'P.O. Box 1234', -- POSTALADDRESS
    '123 Main Street', -- PHYSICALADDRESS
    'Dar es Salaam', -- REGION
    'Ilala', -- DISTRICT
    'Upanga', -- WARD
    'Main Street', -- STREET
    '456', -- HOUSENUMBER
    '12345', -- POSTALCODE
    'Tanzania', -- COUNTRY
    '-6.7924,39.2083', -- GPSCOORDINATES
    'Jane Doe', -- NEXTOFKINNAME
    'Spouse', -- NEXTOFKINRELATIONSHIP
    '+255987654321', -- NEXTOFKINMOBILENUMBER
    'jane.doe@email.com', -- NEXTOFKINEMAILADDRESS
    '123 Main Street', -- NEXTOFKINADDRESS
    'Dar es Salaam', -- NEXTOFKINREGION
    'Ilala', -- NEXTOFKINDISTRICT
    'Upanga', -- NEXTOFKINWARD
    'Main Street', -- NEXTOFKINSTREET
    '456', -- NEXTOFKINHOUSENUMBER
    '12345', -- NEXTOFKINPOSTALCODE
    'Tanzania', -- NEXTOFKINCOUNTRY
    '-6.7924,39.2083', -- NEXTOFKINGPSCOORDINATES
    'Verified', -- KYCSTATUS
    '01012022', -- KYCDATE (DDMMYYYY)
    '01012027', -- KYCEXPIRYDATE (DDMMYYYY)
    'Low', -- RISKRATING
    '01012022', -- RISKRATINGDATE (DDMMYYYY)
    'No', -- PEPSTATUS
    '', -- PEPCLASSIFICATION
    '', -- PEPPOSITION
    '', -- PEPCOUNTRY
    '', -- PEPRELATIONSHIP
    'No', -- SANCTIONSSTATUS
    '', -- SANCTIONSLIST
    '', -- SANCTIONSDATE
    '', -- SANCTIONSCOUNTRY
    'Mzimba' -- VILLAGE
);

COMMIT;