-- Script to recreate CBS_SCHEMA tables with proper CREATEDDATE timestamp column

-- Connect to the database
CONNECT TO CBS_DB;

-- Drop existing tables
DROP TABLE CBS_SCHEMA.PERSONAL_DATA_INDIVIDUALS;
DROP TABLE CBS_SCHEMA.ASSET_OWNED_OR_ACQUIRED;

-- Recreate PERSONAL_DATA_INDIVIDUALS table with proper CREATEDDATE timestamp
CREATE TABLE CBS_SCHEMA.PERSONAL_DATA_INDIVIDUALS (
    CUSTOMERIDENTIFICATIONNUMBER VARCHAR(50),
    FIRSTNAME VARCHAR(100),
    MIDDLENAMES VARCHAR(100),
    SURNAME VARCHAR(100),
    GENDER VARCHAR(10),
    DATEOFBIRTH VARCHAR(12),
    MARITALSTATUS VARCHAR(10),
    NUMBEROFDEPENDANTS INTEGER,
    DISABILITYSTATUS VARCHAR(10),
    DISABILITYTYPE VARCHAR(50),
    CITIZENSHIP VARCHAR(50),
    NATIONALITY VARCHAR(50),
    RESIDENCE VARCHAR(50),
    RESIDENCESTATUS VARCHAR(10),
    EMPLOYMENTSTATUS VARCHAR(10),
    OCCUPATION VARCHAR(50),
    EMPLOYERNAME VARCHAR(100),
    EMPLOYERADDRESS VARCHAR(200),
    SECTOREMPLOYER VARCHAR(50),
    INCOMERANGE VARCHAR(10),
    EDUCATIONLEVEL VARCHAR(10),
    IDENTIFICATIONTYPE VARCHAR(10),
    IDENTIFICATIONNUMBER VARCHAR(50),
    ISSUINGCOUNTRY VARCHAR(50),
    ISSUINGAUTHORITY VARCHAR(100),
    ISSUEDATE VARCHAR(12),
    EXPIRYDATE VARCHAR(12),
    MOBILENUMBER VARCHAR(50),
    ALTMOBILENUMBER VARCHAR(50),
    EMAILADDRESS VARCHAR(100),
    ALTEMAILADDRESS VARCHAR(100),
    POSTALADDRESS VARCHAR(200),
    PHYSICALADDRESS VARCHAR(200),
    REGION VARCHAR(50),
    DISTRICT VARCHAR(50),
    WARD VARCHAR(50),
    STREET VARCHAR(100),
    HOUSENUMBER VARCHAR(50),
    POSTALCODE VARCHAR(50),
    COUNTRY VARCHAR(50),
    GPSCOORDINATES VARCHAR(50),
    NEXTOFKINNAME VARCHAR(100),
    NEXTOFKINRELATIONSHIP VARCHAR(50),
    NEXTOFKINMOBILENUMBER VARCHAR(50),
    NEXTOFKINEMAILADDRESS VARCHAR(100),
    NEXTOFKINADDRESS VARCHAR(200),
    NEXTOFKINREGION VARCHAR(50),
    NEXTOFKINDISTRICT VARCHAR(50),
    NEXTOFKINWARD VARCHAR(50),
    NEXTOFKINSTREET VARCHAR(100),
    NEXTOFKINHOUSENUMBER VARCHAR(50),
    NEXTOFKINPOSTALCODE VARCHAR(50),
    NEXTOFKINCOUNTRY VARCHAR(50),
    NEXTOFKINGPSCOORDINATES VARCHAR(50),
    KYCSTATUS VARCHAR(10),
    KYCDATE VARCHAR(12),
    KYCEXPIRYDATE VARCHAR(12),
    RISKRATING VARCHAR(10),
    RISKRATINGDATE VARCHAR(12),
    PEPSTATUS VARCHAR(10),
    PEPCLASSIFICATION VARCHAR(10),
    PEPPOSITION VARCHAR(100),
    PEPCOUNTRY VARCHAR(50),
    PEPRELATIONSHIP VARCHAR(10),
    SANCTIONSSTATUS VARCHAR(10),
    SANCTIONSLIST VARCHAR(100),
    SANCTIONSDATE VARCHAR(12),
    SANCTIONSCOUNTRY VARCHAR(50),
    VILLAGE VARCHAR(50),
    CREATEDDATE TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP
);

-- Recreate ASSET_OWNED_OR_ACQUIRED table with proper CREATEDDATE timestamp (with corrected fields to match PostgreSQL structure)
CREATE TABLE CBS_SCHEMA.ASSET_OWNED_OR_ACQUIRED (
    ASSETCATEGORY VARCHAR(10),
    ASSETTYPE VARCHAR(50),
    ACQUISITIONDATE VARCHAR(12),
    CURRENCY VARCHAR(50),
    ORGCOSTVALUE DECIMAL(15,2),
    USDCOSTVALUE DECIMAL(15,2),
    TZSCOSTVALUE DECIMAL(15,2),
    ALLOWANCEPROBABLELOSS DECIMAL(15,2),
    BOTPROVISION DECIMAL(15,2),
    CREATEDDATE TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP
);

-- Import the backed up data
IMPORT FROM /tmp/personal_data.del OF DEL INSERT INTO CBS_SCHEMA.PERSONAL_DATA_INDIVIDUALS;
IMPORT FROM /tmp/asset_data.del OF DEL INSERT INTO CBS_SCHEMA.ASSET_OWNED_OR_ACQUIRED;

TERMINATE;