global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@mcb.co.tz'
  smtp_auth_username: 'alerts@mcb.co.tz'
  smtp_auth_password: 'your-email-password'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'

- name: 'critical-alerts'
  email_configs:
  - to: 'ops-team@mcb.co.tz'
    subject: 'CRITICAL: MCB Data Integration Alert'
    body: |
      Alert: {{ .GroupLabels.alertname }}
      Summary: {{ .CommonAnnotations.summary }}
      Description: {{ .CommonAnnotations.description }}
      
      Details:
      {{ range .Alerts }}
      - Instance: {{ .Labels.instance }}
      - Severity: {{ .Labels.severity }}
      - Started: {{ .StartsAt }}
      {{ end }}
  
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    channel: '#mcb-alerts'
    title: 'CRITICAL: MCB Data Integration Alert'
    text: |
      Alert: {{ .GroupLabels.alertname }}
      {{ range .Alerts }}
      Instance: {{ .Labels.instance }}
      {{ end }}

- name: 'warning-alerts'
  email_configs:
  - to: 'dev-team@mcb.co.tz'
    subject: 'WARNING: MCB Data Integration Alert'
    body: |
      Alert: {{ .GroupLabels.alertname }}
      Summary: {{ .CommonAnnotations.summary }}
      Description: {{ .CommonAnnotations.description }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
